import type { booking } from "../types/bookingTypes";

const today = new Date();

export const dummyBookings: booking[] = [
  {
    name: "John Smith",
    checkIn: new Date("2026-03-15"),
    checkOut: new Date("2026-03-18"),
    nights: 3,
    platformId: "BOOK",
    roomId: "A101",
    price: 4500,
    paymentMethod: "OTA",
    note: "Late arrival around 10pm",
    deposit: 1000,
    depositRepaid: false,
    staffUsername: "admin",
    bookingId: "BK001",
  },
  {
    name: "Maria Gonzalez",
    checkIn: new Date("2026-03-20"),
    checkOut: new Date("2026-03-22"),
    nights: 2,
    platformId: "AGDA",
    roomId: "B203",
    price: 3200,
    paymentMethod: "Card",
    note: "",
    deposit: 0,
    depositRepaid: false,
    staffUsername: "mint",
    bookingId: "BK002",
  },
  {
    name: "David Lee",
    checkIn: new Date("2026-03-12"),
    checkOut: new Date("2026-03-14"),
    nights: 2,
    platformId: "TRVL",
    roomId: "A102",
    price: 3000,
    paymentMethod: "Transfer",
    note: "Airport pickup requested",
    deposit: 500,
    depositRepaid: true,
    staffUsername: "admin",
    bookingId: "BK003",
  },
  {
    name: "Emma Brown",
    checkIn: new Date("2026-03-25"),
    checkOut: new Date("2026-03-30"),
    nights: 5,
    platformId: "HSTL",
    roomId: "C301",
    price: 7000,
    paymentMethod: "Cash",
    note: "Extended stay possible",
    deposit: 2000,
    depositRepaid: false,
    staffUsername: "bank",
    bookingId: "BK004",
  },
  {
    name: "Kenji Tanaka",
    checkIn: new Date("2026-04-01"),
    checkOut: new Date("2026-04-04"),
    nights: 3,
    platformId: "BOOK",
    roomId: "A103",
    price: 4800,
    paymentMethod: "OTA",
    note: "",
    deposit: 0,
    depositRepaid: false,
    staffUsername: "mint",
    bookingId: "BK005",
  },
  {
    name: "Sophie Dubois",
    checkIn: new Date("2026-03-28"),
    checkOut: new Date("2026-03-29"),
    nights: 1,
    platformId: "AGDA",
    roomId: "B201",
    price: 1500,
    paymentMethod: "Unpaid",
    note: "Pay at property",
    deposit: 0,
    depositRepaid: false,
    staffUsername: "admin",
    bookingId: "BK006",
  },
  {
    name: "Michael Chen",
    checkIn: new Date("2026-03-18"),
    checkOut: new Date("2026-03-21"),
    nights: 3,
    platformId: "TRVL",
    roomId: "C302",
    price: 4200,
    paymentMethod: "Card",
    note: "",
    deposit: 1000,
    depositRepaid: true,
    staffUsername: "bank",
    bookingId: "BK007",
  },
];
